project:
  type: website
  title: "FINKA_2025"

editor: visual
website:
  title: "FINKA 2025"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: FINKA_2025.qmd
        text: FINKA_2025
      - href: finka_2025_präsentationen.qmd
        text: Präsentationen  # optional: give it a readable label too

format:
  html:
    theme: cosmo
    toc: true